### ISSUE TITLE
VerifiableCredential.Builder: allow setting json string properties

### ISSUE THREAD

**Issue by BenjaminPiette** [elastos/Elastos.DID.JS.SDK#60]
Currently, builder.properties() allows only JSONObjects. 
We need to enable JSONObject | string as parameter and parse the string as json in that case, like the Java SDK allows.

![image](https://user-images.githubusercontent.com/7567594/119067376-86496000-ba14-11eb-8c55-427308263ab5.png)

**Comment by rtrapp** [comment]
Already implemented
